"""add yarn ledger entries

Revision ID: 583406bcaf6e
Revises: 81cd25e835d6
Create Date: 2026-08-26 21:01:58.658317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db.base  # GUID custom type used by generated columns below


# revision identifiers, used by Alembic.
revision: str = '583406bcaf6e'
down_revision: Union[str, None] = '81cd25e835d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('yarn_ledger_entries',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('party_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('movement_type', sa.Enum('received', 'returned', 'dispatched', name='yarnmovementtype'), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('igp_number', sa.String(length=30), nullable=True),
    sa.Column('ogp_number', sa.String(length=30), nullable=True),
    sa.Column('yarn_count', sa.String(length=30), nullable=False),
    sa.Column('bags', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fabric_description', sa.String(length=100), nullable=True),
    sa.Column('knitting_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('loss_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('loss_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('payment_status', sa.Enum('pending', 'partial', 'paid', 'overdue', 'cancelled', name='paymentstatus'), nullable=False),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('created_by', app.db.base.GUID(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_yarn_ledger_entries_created_by_users')),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], name=op.f('fk_yarn_ledger_entries_party_id_parties')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_yarn_ledger_entries'))
    )
    op.create_index(op.f('ix_yarn_ledger_entries_date'), 'yarn_ledger_entries', ['date'], unique=False)
    op.create_index(op.f('ix_yarn_ledger_entries_party_id'), 'yarn_ledger_entries', ['party_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_yarn_ledger_entries_party_id'), table_name='yarn_ledger_entries')
    op.drop_index(op.f('ix_yarn_ledger_entries_date'), table_name='yarn_ledger_entries')
    op.drop_table('yarn_ledger_entries')
    # ### end Alembic commands ###
