"""initial schema

Revision ID: 81cd25e835d6
Revises: 
Create Date: 2026-08-26 17:08:30.084647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db.base


# revision identifiers, used by Alembic.
revision: str = '81cd25e835d6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('employee_code', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('guardian_name', sa.String(length=255), nullable=True),
    sa.Column('national_id', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('joining_date', sa.Date(), nullable=True),
    sa.Column('employment_type', sa.Enum('full_time', 'part_time', 'contract', 'intern', name='employmenttype'), nullable=True),
    sa.Column('status', sa.Enum('candidate', 'active', 'inactive', 'resigned', 'terminated', name='employeestatus'), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deactivated_by', app.db.base.GUID(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employees'))
    )
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=False)
    op.create_index(op.f('ix_employees_employee_code'), 'employees', ['employee_code'], unique=True)
    op.create_index(op.f('ix_employees_national_id'), 'employees', ['national_id'], unique=True)
    op.create_index(op.f('ix_employees_phone'), 'employees', ['phone'], unique=False)
    op.create_table('permissions',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions')),
    sa.UniqueConstraint('module', 'action', name='uq_permissions_module_action')
    )
    op.create_table('roles',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name'))
    )
    op.create_table('users',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('attendance_records',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('employee_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('check_in', sa.Time(), nullable=True),
    sa.Column('check_out', sa.Time(), nullable=True),
    sa.Column('status', sa.Enum('present', 'absent', 'late', 'half_day', 'leave', 'holiday', 'weekend', name='attendancestatus'), nullable=False),
    sa.Column('working_hours', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_attendance_records_employee_id_employees')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance_records')),
    sa.UniqueConstraint('employee_id', 'date', name='uq_attendance_employee_date')
    )
    op.create_index(op.f('ix_attendance_records_date'), 'attendance_records', ['date'], unique=False)
    op.create_index(op.f('ix_attendance_records_employee_id'), 'attendance_records', ['employee_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('user_id', app.db.base.GUID(length=36), nullable=True),
    sa.Column('action', sa.Enum('created', 'updated', 'deactivated', 'reactivated', 'reconciled', 'exported', name='auditaction'), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('record_type', sa.String(length=50), nullable=False),
    sa.Column('record_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_log_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index(op.f('ix_audit_log_record_id'), 'audit_log', ['record_id'], unique=False)
    op.create_index(op.f('ix_audit_log_record_type'), 'audit_log', ['record_type'], unique=False)
    op.create_table('documents',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('owner_type', sa.Enum('party', 'employee', 'transaction', name='documentownertype'), nullable=False),
    sa.Column('owner_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('uploaded_by', app.db.base.GUID(length=36), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_documents_uploaded_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    op.create_index(op.f('ix_documents_owner_id'), 'documents', ['owner_id'], unique=False)
    op.create_table('parties',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('party_code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('customer', 'vendor', 'both', name='partytype'), nullable=False),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', name='partystatus'), nullable=False),
    sa.Column('opening_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_by', app.db.base.GUID(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source', sa.Enum('file_a', 'file_b', 'merged', 'manual', name='partysource'), nullable=False),
    sa.Column('import_raw', sa.JSON(), nullable=True),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deactivated_by', app.db.base.GUID(length=36), nullable=True),
    sa.Column('merged_into', app.db.base.GUID(length=36), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_parties_created_by_users')),
    sa.ForeignKeyConstraint(['deactivated_by'], ['users.id'], name=op.f('fk_parties_deactivated_by_users')),
    sa.ForeignKeyConstraint(['merged_into'], ['parties.id'], name=op.f('fk_parties_merged_into_parties')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parties'))
    )
    op.create_index(op.f('ix_parties_normalized_name'), 'parties', ['normalized_name'], unique=False)
    op.create_index(op.f('ix_parties_party_code'), 'parties', ['party_code'], unique=True)
    op.create_table('role_permissions',
    sa.Column('role_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('permission_id', app.db.base.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles')),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permissions'))
    )
    op.create_table('salary_history',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('employee_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_by', app.db.base.GUID(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_salary_history_created_by_users')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_salary_history_employee_id_employees')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_salary_history'))
    )
    op.create_index(op.f('ix_salary_history_employee_id'), 'salary_history', ['employee_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('role_id', app.db.base.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_roles'))
    )
    op.create_table('transactions',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('transaction_code', sa.String(length=20), nullable=False),
    sa.Column('party_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('entry_type', sa.Enum('receivable', 'payable', 'payment_in', 'payment_out', 'adjustment', name='transactionentrytype'), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('payment_status', sa.Enum('pending', 'partial', 'paid', 'overdue', 'cancelled', name='paymentstatus'), nullable=False),
    sa.Column('document_id', app.db.base.GUID(length=36), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', app.db.base.GUID(length=36), nullable=True),
    sa.Column('updated_by', app.db.base.GUID(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_transactions_created_by_users')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_transactions_document_id_documents')),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], name=op.f('fk_transactions_party_id_parties')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_transactions_updated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions'))
    )
    op.create_index(op.f('ix_transactions_date'), 'transactions', ['date'], unique=False)
    op.create_index(op.f('ix_transactions_party_id'), 'transactions', ['party_id'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_code'), 'transactions', ['transaction_code'], unique=True)
    op.create_table('reconciliation_records',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('reconciliation_code', sa.String(length=20), nullable=False),
    sa.Column('party_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('transaction_id', app.db.base.GUID(length=36), nullable=True),
    sa.Column('expected_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('actual_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('difference', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('status', sa.Enum('matched', 'partially_matched', 'unmatched', 'pending', 'reviewed', name='reconciliationstatus'), nullable=False),
    sa.Column('reconciliation_date', sa.Date(), nullable=True),
    sa.Column('reviewed_by', app.db.base.GUID(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], name=op.f('fk_reconciliation_records_party_id_parties')),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name=op.f('fk_reconciliation_records_reviewed_by_users')),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_reconciliation_records_transaction_id_transactions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reconciliation_records'))
    )
    op.create_index(op.f('ix_reconciliation_records_party_id'), 'reconciliation_records', ['party_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_records_reconciliation_code'), 'reconciliation_records', ['reconciliation_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reconciliation_records_reconciliation_code'), table_name='reconciliation_records')
    op.drop_index(op.f('ix_reconciliation_records_party_id'), table_name='reconciliation_records')
    op.drop_table('reconciliation_records')
    op.drop_index(op.f('ix_transactions_transaction_code'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_party_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_date'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_salary_history_employee_id'), table_name='salary_history')
    op.drop_table('salary_history')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_parties_party_code'), table_name='parties')
    op.drop_index(op.f('ix_parties_normalized_name'), table_name='parties')
    op.drop_table('parties')
    op.drop_index(op.f('ix_documents_owner_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_audit_log_record_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_record_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_attendance_records_employee_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_date'), table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_employees_phone'), table_name='employees')
    op.drop_index(op.f('ix_employees_national_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_employee_code'), table_name='employees')
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
