"""Add gate pass model

Revision ID: e1b76fe14f8e
Revises: 583406bcaf6e
Create Date: 2026-08-28 15:14:49.756146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db.base  # GUID custom type used by generated columns below


# revision identifiers, used by Alembic.
revision: str = 'e1b76fe14f8e'
down_revision: Union[str, None] = '583406bcaf6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gate_passes',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('gate_pass_number', sa.String(length=50), nullable=False),
    sa.Column('type', sa.Enum('igp', 'ogp', name='gatepasstype'), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('party_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('returnable', sa.Boolean(), nullable=False),
    sa.Column('material', sa.String(length=255), nullable=False),
    sa.Column('yarn_count', sa.String(length=50), nullable=True),
    sa.Column('yarn_type', sa.String(length=50), nullable=True),
    sa.Column('bags_rolls', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('weight', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('yarn_return', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('expected_return', sa.Date(), nullable=True),
    sa.Column('store_destination', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('pending', 'received', 'completed', name='gatepassstatus'), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_by', app.db.base.GUID(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_gate_passes_created_by_users')),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], name=op.f('fk_gate_passes_party_id_parties')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gate_passes'))
    )
    op.create_index(op.f('ix_gate_passes_date'), 'gate_passes', ['date'], unique=False)
    op.create_index(op.f('ix_gate_passes_gate_pass_number'), 'gate_passes', ['gate_pass_number'], unique=True)
    op.create_index(op.f('ix_gate_passes_party_id'), 'gate_passes', ['party_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gate_passes_party_id'), table_name='gate_passes')
    op.drop_index(op.f('ix_gate_passes_gate_pass_number'), table_name='gate_passes')
    op.drop_index(op.f('ix_gate_passes_date'), table_name='gate_passes')
    op.drop_table('gate_passes')
    # ### end Alembic commands ###
